name: 'Tests - Setup YQ Action'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'action.yaml'
      - '.github/workflows/tests.yaml'
      - 'scripts/unixish.sh'
      - 'scripts/windowsish.ps1'

  pull_request:
    branches:
      - main

jobs:
  test-linux:
    strategy:
      matrix:
        image:
#          - "ubuntu-latest"
#          - "ubuntu-20.04"
#          - "ubuntu-22.04"
#          - "macos-latest"
#          - "macos-11"
#          - "macos-12"
          - "windows-latest"
#          - "windows-2022"
#          - "windows-2019"
        download-compressed:
          - 'true'
          - 'false'
        force:
          - 'true'
          - 'false'
    name: "Test Action - (img: ${{ matrix.image }}; dlcmp: ${{ matrix.download-compressed }}; force: ${{ matrix.force }})"
    runs-on: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup yq
        id: setup-yq
        uses: dcarbone/setup-yq-action@main
        with:
          force: '${{ matrix.force }}'
          download-compressed: '${{ matrix.download-compressed }}'

      - name: Check yq - Unix-ish
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          which yq
          yq --version

      - name: Check Outputs - Unix-ish
        if: runner.os == 'Linux' || runner.os == 'macOS'
        shell: bash -e {0}
        run: |
          _installed='${{ steps.setup-yq.outputs.installed }}'
          _err=
          if [[ '${{ matrix.force }}' == 'true' ]]; then
            if [[ '${{ steps.setup-yq.outputs.installed }}' != 'true' ]]; then
              echo 'Unexpected value for "installed":'
              echo 'Expected:   "true"'
              echo 'Actual:     "${{ steps.setup-yq.outputs.installed }}"'
              _err=1
            fi
          else
            if [[ '${{ steps.setup-yq.outputs.found }}' == 'true' ]]; then
              if [[ '${{ steps.setup-yq.outputs.installed }}' != 'false' ]]; then
                echo 'Unexpected value for "installed":'
                echo 'Expected:   "false"'
                echo 'Actual:     "${{ steps.setup-yq.outputs.installed }}"'
                _err=1
              fi
            else
              if [[ '${{ steps.setup-yq.outputs.installed }}' != 'true' ]]; then
                echo 'Unexpected value for "installed":'
                echo 'Expected:   "true"'
                echo 'Actual:     "${{ steps.setup-yq.outputs.installed }}"'
                _err=1
              fi
            fi
          fi
          if [ -n "${_err}" ]; then exit 1; fi;


      - name: Check yq - Windows-ish
        if: runner.os == 'Windows'
        run: |
          Get-ChildItem "$Env:RUNNER_TOOL_CACHE\yq" -Recurse
          Get-Command "yq.exe"
          yq.exe --version

      - name: Check Outputs - Windows-ish
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Write-Host "do something"
